version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-service
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: ./backend-services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - products
      - orders

  products:
    build:
      context: ./backend-services/product-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  orders:
    build:
      context: ./backend-services/order-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=your-rds-endpoint.amazonaws.com
      - DB_USER=your-rds-username
      - DB_PASSWORD=your-rds-password
      - DB_NAME=gogetyourgreen
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gogetyourgreen
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: 