apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 배포에 포함할 리소스 파일들을 지정합니다.
resources:
  - frontend-deployment.yaml
  - api-gateway-deployment.yaml
  - product-service-deployment.yaml
  - order-service-deployment.yaml
  - ingress.yaml

# 이미지 정보를 한 곳에서 관리합니다.
# 팀원은 이 부분의 newName과 newTag만 수정하면 됩니다.
images:
  - name: gogetyourgreen-frontend
    newName: sususu25/gogetyourgreen-frontend
    newTag: v1
  - name: gogetyourgreen-api-gateway
    newName: sususu25/api-gateway
    newTag: latest
  - name: gogetyourgreen-product-service
    newName: sususu25/gogetyourgreen-product
    newTag: v1
  - name: gogetyourgreen-order-service
    newName: sususu25/order-service
    newTag: latest 