apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: gogetyourgreen-order-service # Kustomize가 이 이름을 sususu25/order-service:latest로 바꿉니다.
        ports:
        - containerPort: 3002
        env:
        - name: DB_HOST
          value: "mysqldb"
        envFrom:
        - secretRef:
            name: db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002 